from deucalion.strategies.direct_target_scraping import DirectTargetScraping
from deucalion.strategies.prometheus_server_query import PrometheusServerQuerying
from deucalion.strategies.prometheus_target_scraping import PrometheusTargetScraping
