alertManager:
  appName: "alert-manager"
  replicas: 1
  image:
    name: "prom/alertmanager"
    tag: "latest"
    pullPolicy: "Always"
  containerPort: 9093

certManager:
  namespace: cert-manager
  groupName: "acme.ilabt.imec.be"
  serviceAccountName: cert-manager

webhook:
  appName: "deucalion-injector"
  replicas: 1

  image:
    name: "pimoens/deucalion-injector"
    tag: "latest"
    pullPolicy: "Always"

  sidecar:
    image:
      name: "hello-world"
      tag: "latest"
      pullPolicy: "Always"

    serviceAccountName: "deucalion-injector-sa"
    alertName: "deucalion_event"

namespace: "deucalion-system"