namespace: "deucalion-system"

alertManager:
  appName: "alert-manager"
  replicas: 1
  image:
    name: "prom/alertmanager"
    tag: "latest"
    pullPolicy: "Always"
  containerPort: 9093

certManager:
  namespace: cert-manager
  groupName: "acme.ilabt.imec.be"
  serviceAccountName: cert-manager

sidecar:
  image:
    name: "pimoens/deucalion-example"
    tag: "latest"
    pullPolicy: "Always"

  strategy: "prometheus_sidecar"
  scrape_interval: 15
  serviceAccountName: "deucalion-injector-sa"
  alertName: "deucalion_event"

webhook:
  appName: "deucalion-injector"
  replicas: 1

  image:
    name: "pimoens/deucalion-injector"
    tag: "latest"
    pullPolicy: "Always"
