alertManager:
  appName: "alert-manager"
  replicas: 1
  image: "prom/alertmanager:latest"
  imagePullPolicy: "Always"

certManager:
  namespace: cert-manager
  groupName: "acme.ilabt.imec.be"
  serviceAccountName: cert-manager

admissionController:
  webhookService:
    args:
      defaultSidecarImage: "hello-world::latest"
      serviceAccountName: "deucalion-service-account"
      alertName: "deucalion_event"
      alertManagerPort: 9093

    volumes: 
      tlsCertsVolumeName: "webhook-tls-certs"
    imagePullPolicy: "Always"
    image: "pimoens/deucalion-injector:latest"
    replicas: 1
    mutateEndpoint: "/mutate"
    appName: "deucalion-injector"

  timeoutSeconds: 5
  matchabel: "deucalion-injection"
  matchLabelValue: "enabled"

namespace: "deucalion-system"
applicationNamespace: "sock-shop"