admissionController:
  webhookService:
    args:
      defaultSidecarImage: "pimoens/deucalion-app:0.0.1"
      serviceAccountName: "deucalion-service-account"
      alertName: "deucalion_event"
      alertManagerPort: 9093

    volumes: 
      tlsCertsVolumeName: "webhook-tls-certs"
    imagePullPolicy: "Always"
    image: "pimoens/deucalion-injector:latest"
    replicas: 1
    mutateEndpoint: "/mutate"
    appName: "deucalion-injector"

  timeoutSeconds: 5
  matchabel: "deucalion-injection"
  matchLabelValue: "enabled"

alertManager:
  appName: "alert-manager"
  replicas: 1
  image: "prom/alertmanager:latest"
  imagePullPolicy: "Always"

namespace: "deucalion-system"
applicationNamespace: "sock-shop"