apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.alertManager.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.alertManager.appName }}
  ports:
    - port: {{ .Values.alertManager.containerPort }}
      targetPort: http
      name: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.alertManager.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.alertManager.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.alertManager.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.alertManager.appName }}
    spec:
      containers:
      - name: {{ .Values.alertManager.appName }}
        image: {{ .Values.alertManager.image.name }}:{{ .Values.alertManager.image.tag }}
        imagePullPolicy: {{ .Values.alertManager.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.alertManager.containerPort }}
          name: http
