apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.admissionController.webhookService.appName }}-certificate
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.admissionController.webhookService.appName }}-certificate

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - jetstack
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - {{ .Values.admissionController.webhookService.appName }}.{{ .Values.namespace }}
  # Issuer references are always required.
  issuerRef:
    name: selfsigned
