apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.admissionController.webhookService.appName }}-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: "{{ .Values.admissionController.webhookService.tlsCrt }}"
  tls.key: "{{ .Values.admissionController.webhookService.tlsKey }}"
  