apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.webhook.appName }}-selfsign
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.webhook.appName }}-ca
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ .Values.webhook.appName }}-ca
  duration: 43800h # 5y
  issuerRef:
    name: {{ .Values.webhook.appName }}-selfsign
  commonName: "ca.deucalion-injector.cert-manager"
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.webhook.appName }}-ca
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ca:
    secretName: {{ .Values.webhook.appName }}-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.webhook.appName }}-webhook-tls
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.webhook.appName }}-webhook-tls
  duration: 8760h # 1y
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - {{ .Values.webhook.appName }}
    - {{ .Values.webhook.appName }}.{{ .Values.namespace }}
    - {{ .Values.webhook.appName }}.{{ .Values.namespace }}.svc
    - {{ .Values.webhook.appName }}.{{ .Values.namespace }}.svc.cluster.local
  # Issuer references are always required.
  issuerRef:
    name: {{ .Values.webhook.appName }}-ca
