apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.webhook.sidecar.serviceAccountName }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.webhook.appName }}-cluster-role
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - pods
      - componentstatuses
      - deployments
      - endpoints
      - jobs
      - nodes
      - services
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.webhook.appName }}-role-binding
subjects:
  - name: {{ .Values.webhook.sidecar.serviceAccountName }}
    namespace: {{ .Values.namespace }}
    kind: ServiceAccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.webhook.appName }}-cluster-role
