apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: deucalion-injector
  ports:
    - port: 443
      targetPort: tls
      name: application