apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.appName }}
  labels:
    app: {{ .Values.webhook.appName }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Values.namespace }}/{{ .Values.webhook.appName }}-webhook-tls"
webhooks:
  - name: {{ .Values.webhook.appName }}.{{ .Values.namespace }}.svc.cluster.local
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1", "v1beta1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["pods"]
        scope:       "*"
    namespaceSelector:
      matchLabels:
        deucalion-injection: "enabled"
    clientConfig:
      service:
        namespace: {{ .Values.namespace }}
        name: {{ .Values.webhook.appName }}
        path: "/mutate"
        
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5