apiVersion: v1
kind: ConfigMap
metadata:
  name: 'deucalion-prometheus-sidecar-configmap'
data:
  deucalion_config.yaml: |
    config:
      scrape_interval: {{ .Values.sidecar.scrape_interval }}
      type: 'prometheus_sidecar'

    alert_manager:
      alert_name: '{{ .Values.sidecar.alertName }}'
      host: '{{ .Values.alertManager.appName }}.{{ .Values.nameSpace }}.svc.cluster.local'
      port: {{ .Values.alertManager.containerPort }}