# Docker Compose
alert_manager:
  alert_name: 'deucalion_event_alert'
  host: 'alert-manager'
  port: 9093

config:
  scrape_interval: 5

  metric_provider: 'prometheus_targets'
  target_provider: 'config'
  targets:
    - host: 'node-exporter'
      port: 9100
      path: 'metrics'
